In [1]:
import pandas as pd

ImportError: Unable to import required dependencies:
numpy:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
  * The NumPy version is: "1.24.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Users/denisdavydov/Library/Python/3.9/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 0x0002): tried: '/Users/denisdavydov/Library/Python/3.9/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/denisdavydov/Library/Python/3.9/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so' (no such file), '/Users/denisdavydov/Library/Python/3.9/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

In [3]:
df = pd.read_csv("kc_house_data.csv", encoding='cp1251')

In [4]:
clients = pd.DataFrame({
'client_id': [1459, 4684, 3498, 3942, 4535, 2308, 2866, 2765, 1472, 4236, 2295, 939, 3840, 280, 20, 4332, 3475, 4213, 3113, 4809, 2134, 2242, 2068, 4929, 1384, 1589, 3317, 2260, 1727, 1764, 1611, 1474],
'house_id': [8965450190, 6823100225, 5104540330, 2131701075, 1522700060, 1189000207, 6821600300, 7137950720, 9510920050, 6131600255, 5428000070, 1788800910, 8100400160, 3123049142, 6306800010, 5083000375, 7920100025, 1951600150, 809001400, 339600110, 1622049154, 1099600250, 8563000110, 2768100205, 3995700435, 8861700030, 3303980210, 7731100066, 8146100580, 825069097, 3889100029, 9524100196]
})

In [5]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [6]:
#2.1 Присоедините к таблице clients данные по домам через метод join, house_id - это признак id в датафрейме с домами
clients_id = clients.set_index('client_id')
clients_id.join(df)

,house_id,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
client_id,,,,,,,,,,,,,,,,,,,,,
1459,8965450190,3275860270,20141022T000000,755000.0,3,2.25,3020,13031,2.0,0,...,9,3020,0,1989,0,98052,47.6897,-122.098,2480,10204
4684,6823100225,9268200600,20140519T000000,413500.0,2,1.00,770,4000,1.0,0,...,5,770,0,1924,0,98117,47.6959,-122.364,1420,5040
3498,5104540330,9547204350,20140519T000000,690000.0,3,2.00,1610,5100,1.5,0,...,8,1610,0,1940,0,98115,47.6825,-122.307,1740,5100
3942,2131701075,8861500015,20140520T000000,675000.0,3,2.25,1990,10260,2.0,0,...,8,1990,0,1987,0,98052,47.6801,-122.115,1990,10260
4535,1522700060,5556300076,20150423T000000,1442500.0,3,2.25,2630,9705,2.5,0,...,8,2630,0,1987,0,98052,47.6485,-122.121,2640,14284
2308,1189000207,6788200800,20150507T000000,1185000.0,4,2.75,2850,3000,2.5,0,...,9,2530,320,2003,0,98112,47.6406,-122.304,2083,4500
2866,6821600300,3275730110,20140908T000000,425000.0,3,2.25,1630,10500,1.0,0,...,7,1100,530,1974,0,98034,47.7176,-122.236,1640,9794
2765,7137950720,6662410070,20150414T000000,420000.0,4,2.25,2030,12000,2.0,0,...,7,2030,0,1977,0,98011,47.7699,-122.168,2190,9900
1472,9510920050,2724069070,20150220T000000,519500.0,4,2.00,1540,17859,1.0,0,...,6,1540,0,1964,0,98027,47.5326,-122.032,1390,9688
4236,6131600255,1698900195,20140902T000000,710000.0,3,2.00,1880,3000,1.0,0,...,8,1040,840,1931,0,98109,47.6418,-122.351,1790,3000
2295,5428000070,8712100320,20140728T000000,585000.0,5,2.75,2350,4178,1.5,0,...,8,1520,830,1922,2015,98112,47.6388,-122.300,1920,4178
939,1788800910,1324079046,20150120T000000,350000.0,3,2.25,1580,47916,1.0,0,...,7,1580,0,1979,0,98024,47.5583,-121.852,1980,75358
3840,8100400160,522059013,20140612T000000,173000.0,2,1.00,820,10450,1.0,0,...,7,820,0,1965,0,98055,47.4261,-122.199,1240,11200
280,3123049142,1722059235,20140703T000000,304900.0,4,1.75,2600,11325,1.0,0,...,7,1610,990,1969,0,98031,47.3954,-122.206,1720,11088
20,6306800010,6300500875,20140514T000000,385000.0,4,1.75,1620,4980,1.0,0,...,7,860,760,1947,0,98133,47.7025,-122.341,1400,4980
4332,5083000375,1626079066,20140806T000000,290000.0,2,1.00,1120,217800,1.0,0,...,6,1120,0,1976,0,98019,47.7378,-121.912,1480,217800
3475,7920100025,9550202870,20150209T000000,417000.0,2,1.75,1090,4590,1.0,0,...,7,790,300,1915,0,98105,47.6677,-122.324,1390,4080
4213,1951600150,8665050490,20140924T000000,480680.0,3,2.50,1730,4924,2.0,0,...,8,1730,0,1996,0,98029,47.5672,-122.005,1610,4313
3113,809001400,9510970300,20140923T000000,775000.0,4,2.50,3310,5101,2.0,0,...,9,3310,0,2005,0,98052,47.6649,-122.080,3010,5176
4809,339600110,8643000225,20150506T000000,225000.0,5,1.50,1790,11656,2.0,0,...,7,1790,0,1963,0,98198,47.3961,-122.308,2040,9790
2134,1622049154,9264901040,20140516T000000,239900.0,4,2.25,1860,7000,1.0,0,...,8,1120,740,1979,0,98023,47.3127,-122.339,1990,8937
2242,1099600250,5104531820,20140602T000000,525000.0,4,2.50,2910,7631,2.0,0,...,9,2910,0,2006,0,98038,47.3552,-122.001,3190,5552
2068,8563000110,1771100240,20140925T000000,361000.0,3,1.75,1650,11220,1.0,0,...,7,1650,0,1969,0,98077,47.7567,-122.071,1340,10129
4929,2768100205,9830200380,20140917T000000,653000.0,3,3.00,3040,5067,3.0,0,...,10,3040,0,1993,0,98118,47.5409,-122.267,1820,5998
1384,3995700435,6392003490,20140723T000000,433500.0,3,1.00,1230,6000,1.0,0,...,7,780,450,1937,0,98115,47.6839,-122.281,1570,5000
1589,8861700030,2004100075,20150326T000000,332000.0,2,1.00,1150,8138,1.0,0,...,7,1150,0,1954,0,98155,47.7370,-122.325,1300,8139
3317,3303980210,2821049048,20140603T000000,590000.0,4,4.25,2360,57514,2.0,0,...,8,2360,0,1939,1987,98003,47.2843,-122.294,2037,35733
2260,7731100066,7345000340,20150203T000000,208000.0,3,1.00,1020,6120,1.0,0,...,7,1020,0,1967,0,98002,47.2780,-122.205,1370,8000
1727,8146100580,5088500310,20150312T000000,435000.0,3,2.00,2660,16677,1.0,0,...,9,2210,450,1990,0,98038,47.3689,-122.055,2660,11355
1764,825069097,8565000030,20150429T000000,805000.0,4,2.50,3450,33460,2.0,0,...,9,3450,0,1997,0,98077,47.7673,-122.100,2820,35250
1611,3889100029,9407101840,20140620T000000,378000.0,4,2.50,1890,12236,1.0,0,...,7,1230,660,1978,0,98045,47.4491,-121.780,1390,11360
1474,9524100196,2413301070,20150324T000000,280000.0,4,2.25,2100,8075,2.0,0,...,8,2100,0,1978,0,98003,47.3251,-122.329,2100,7464

In [7]:
#2.2 Присоедините к таблице clients данные по домам через метод merge
merged = clients.merge(df, left_on='client_id', right_on=df.index, how='left')
merged

,client_id,house_id,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,1459,8965450190,3275860270,20141022T000000,755000.0,3,2.25,3020,13031,2.0,...,9,3020,0,1989,0,98052,47.6897,-122.098,2480,10204
1,4684,6823100225,9268200600,20140519T000000,413500.0,2,1.00,770,4000,1.0,...,5,770,0,1924,0,98117,47.6959,-122.364,1420,5040
2,3498,5104540330,9547204350,20140519T000000,690000.0,3,2.00,1610,5100,1.5,...,8,1610,0,1940,0,98115,47.6825,-122.307,1740,5100
3,3942,2131701075,8861500015,20140520T000000,675000.0,3,2.25,1990,10260,2.0,...,8,1990,0,1987,0,98052,47.6801,-122.115,1990,10260
4,4535,1522700060,5556300076,20150423T000000,1442500.0,3,2.25,2630,9705,2.5,...,8,2630,0,1987,0,98052,47.6485,-122.121,2640,14284
5,2308,1189000207,6788200800,20150507T000000,1185000.0,4,2.75,2850,3000,2.5,...,9,2530,320,2003,0,98112,47.6406,-122.304,2083,4500
6,2866,6821600300,3275730110,20140908T000000,425000.0,3,2.25,1630,10500,1.0,...,7,1100,530,1974,0,98034,47.7176,-122.236,1640,9794
7,2765,7137950720,6662410070,20150414T000000,420000.0,4,2.25,2030,12000,2.0,...,7,2030,0,1977,0,98011,47.7699,-122.168,2190,9900
8,1472,9510920050,2724069070,20150220T000000,519500.0,4,2.00,1540,17859,1.0,...,6,1540,0,1964,0,98027,47.5326,-122.032,1390,9688
9,4236,6131600255,1698900195,20140902T000000,710000.0,3,2.00,1880,3000,1.0,...,8,1040,840,1931,0,98109,47.6418,-122.351,1790,3000
10,2295,5428000070,8712100320,20140728T000000,585000.0,5,2.75,2350,4178,1.5,...,8,1520,830,1922,2015,98112,47.6388,-122.300,1920,4178
11,939,1788800910,1324079046,20150120T000000,350000.0,3,2.25,1580,47916,1.0,...,7,1580,0,1979,0,98024,47.5583,-121.852,1980,75358
12,3840,8100400160,522059013,20140612T000000,173000.0,2,1.00,820,10450,1.0,...,7,820,0,1965,0,98055,47.4261,-122.199,1240,11200
13,280,3123049142,1722059235,20140703T000000,304900.0,4,1.75,2600,11325,1.0,...,7,1610,990,1969,0,98031,47.3954,-122.206,1720,11088
14,20,6306800010,6300500875,20140514T000000,385000.0,4,1.75,1620,4980,1.0,...,7,860,760,1947,0,98133,47.7025,-122.341,1400,4980
15,4332,5083000375,1626079066,20140806T000000,290000.0,2,1.00,1120,217800,1.0,...,6,1120,0,1976,0,98019,47.7378,-121.912,1480,217800
16,3475,7920100025,9550202870,20150209T000000,417000.0,2,1.75,1090,4590,1.0,...,7,790,300,1915,0,98105,47.6677,-122.324,1390,4080
17,4213,1951600150,8665050490,20140924T000000,480680.0,3,2.50,1730,4924,2.0,...,8,1730,0,1996,0,98029,47.5672,-122.005,1610,4313
18,3113,809001400,9510970300,20140923T000000,775000.0,4,2.50,3310,5101,2.0,...,9,3310,0,2005,0,98052,47.6649,-122.080,3010,5176
19,4809,339600110,8643000225,20150506T000000,225000.0,5,1.50,1790,11656,2.0,...,7,1790,0,1963,0,98198,47.3961,-122.308,2040,9790
20,2134,1622049154,9264901040,20140516T000000,239900.0,4,2.25,1860,7000,1.0,...,8,1120,740,1979,0,98023,47.3127,-122.339,1990,8937
21,2242,1099600250,5104531820,20140602T000000,525000.0,4,2.50,2910,7631,2.0,...,9,2910,0,2006,0,98038,47.3552,-122.001,3190,5552
22,2068,8563000110,1771100240,20140925T000000,361000.0,3,1.75,1650,11220,1.0,...,7,1650,0,1969,0,98077,47.7567,-122.071,1340,10129
23,4929,2768100205,9830200380,20140917T000000,653000.0,3,3.00,3040,5067,3.0,...,10,3040,0,1993,0,98118,47.5409,-122.267,1820,5998
24,1384,3995700435,6392003490,20140723T000000,433500.0,3,1.00,1230,6000,1.0,...,7,780,450,1937,0,98115,47.6839,-122.281,1570,5000
25,1589,8861700030,2004100075,20150326T000000,332000.0,2,1.00,1150,8138,1.0,...,7,1150,0,1954,0,98155,47.7370,-122.325,1300,8139
26,3317,3303980210,2821049048,20140603T000000,590000.0,4,4.25,2360,57514,2.0,...,8,2360,0,1939,1987,98003,47.2843,-122.294,2037,35733
27,2260,7731100066,7345000340,20150203T000000,208000.0,3,1.00,1020,6120,1.0,...,7,1020,0,1967,0,98002,47.2780,-122.205,1370,8000
28,1727,8146100580,5088500310,20150312T000000,435000.0,3,2.00,2660,16677,1.0,...,9,2210,450,1990,0,98038,47.3689,-122.055,2660,11355
29,1764,825069097,8565000030,20150429T000000,805000.0,4,2.50,3450,33460,2.0,...,9,3450,0,1997,0,98077,47.7673,-122.100,2820,35250
30,1611,3889100029,9407101840,20140620T000000,378000.0,4,2.50,1890,12236,1.0,...,7,1230,660,1978,0,98045,47.4491,-121.780,1390,11360
31,1474,9524100196,2413301070,20150324T000000,280000.0,4,2.25,2100,8075,2.0,...,8,2100,0,1978,0,98003,47.3251,-122.329,2100,7464